# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opscode_ubuntu-14.04_chef-provisionerless"
  config.omnibus.chef_version = :latest
  config.vm.define :develop do |develop|
    develop.vm.network :private_network, ip: "192.168.33.10"
	develop.vm.synced_folder "./application", "/var/www/application/current"
	config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    develop.vm.provision :chef_solo do |chef|
    chef.log_level = "debug"
    chef.cookbooks_path = "./cookbooks"
    chef.json = {
        nginx: {
            docroot: {
            owner: "vagrant",
            group: "vagrant",
            path: "/var/www/application/current/app/webroot",
            force_create: true
            },
            default: {
            fastcgi_params: { CAKE_ENV: "development" }
            },
            test: {
                available: true,
                fastcgi_params: { CAKE_ENV: "test" }
            }
        }
    }
    chef.run_list = %w[
    recipe[apt]
    recipe[phpenv::default]]
end
  end

  config.vm.define :ci do |ci|
    ci.vm.network :private_network, ip: "192.168.33.100"
	config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
ci.vm.provision :chef_solo do |chef|
      chef.log_level = "debug"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            path: "/var/lib/jenkins/jobs/blogapp/workspace/app/webroot",
          },
          default: {
            fastcgi_params: { CAKE_ENV: "development" }
          },
          test: {
            available: true,
            fastcgi_params: { CAKE_ENV: "ci" }
          }
        }
      }
      chef.run_list = %w[
        recipe[apt]
        recipe[phpenv::default]
        recipe[phpenv::composer]
        recipe[phpenv::develop]
        recipe[capistrano]
        recipe[jenkins::default]
        recipe[jenkins::plugin]
      ]
    end
  end

  config.vm.define :deploy do |deploy|
    deploy.vm.network :private_network, ip: "192.168.33.200"
    deploy.vm.hostname = "deploy"
	  config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
    deploy.vm.provision :chef_solo do |chef|
      chef.log_level = "debug"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            owner: "vagrant",
            group: "vagrant",
            path: "/var/www/application/current/app/webroot",
          },
          default: {
            fastcgi_params: {  CAKE_ENV: "production" }
          }
        }
      }
      chef.run_list = %w[
        recipe[apt]
        recipe[phpenv::default]
        recipe[phpenv::composer]
      ]
    end
  end
end
