# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config| 
  config.vm.define "develop" do |develop|
      develop.vm.box = "opscode_unbuntu14"
      develop.vm.network :private_network, ip: "192.168.33.10"
      develop.vm.synced_folder ".", "/var/www/application/current", :create => true, :mount_options => ["dmode=777","fmode=777"]
      develop.vm.host_name = "develop"
  end

  config.vm.define "ci" do |ci|
      ci.vm.box = "opscode_unbuntu14"
      ci.vm.network :private_network, ip: "192.168.33.100"
      ci.vm.host_name = "ci"
  end

 config.vm.define "deploy" do |deploy|
     deploy.vm.box = "opscode_unbuntu14"
     deploy.vm.network :private_network, ip: "192.168.33.200"
     deploy.vm.host_name = "deploy"
 end

end
