# -*- mode: ruby -*-
# vi: set ft=ruby :
# HieuTT - w4 - vagrantfile

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.omnibus.chef_version = :latest
  
#----- develop ----- 
  config.vm.define "develop" do |develop| 
    develop.vm.box = "ubuntu1404"
    develop.vm.network "private_network", ip: "192.168.33.10"
    develop.vm.host_name = "develop"
    develop.vm.synced_folder "./application", "/var/www/application/current"
    
    develop.vm.provision :chef_solo do |chef|
      chef.log_level = "debug"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            owner: "vagrant",
            group: "vagrant",
            path: "/var/www/application/current/app/webroot",
            force_create: true
          },
          default: {
            fastcgi_params: { CAKE_ENV: "development" }
          },
          test: {
            available: true,
            fastcgi_params: { CAKE_ENV: "test" }
          }
        }
      }
      chef.run_list = %w[
        recipe[apt]
        recipe[phpenv::default]]
      end
    end  

#----- ci -----
  config.vm.define "ci" do |ci| 
    ci.vm.box = "ubuntu1404"
    ci.vm.network "private_network", ip: "192.168.33.100"
    ci.vm.host_name = "ci"
        
    ci.vm.provision :chef_solo do |chef|
      chef.log_level = "debug"
      chef.run_list = %w[
      	recipe[apt]
      	recipe[java]
        recipe[jenkins::master]
        recipe[jenkins::plugins]]
       end
    end  

#----- deploy -----
 config.vm.define "deploy" do |deploy| 
    deploy.vm.box = "ubuntu1404"
    deploy.vm.network "private_network", ip: "192.168.33.200"
    deploy.vm.host_name = "deploy"
    deploy.vm.synced_folder "./application_deploy", "/var/www/application/current"
    
    deploy.vm.provision :chef_solo do |chef|
      chef.log_level = "debug"
      chef.cookbooks_path = "./cookbooks"
      chef.json = {
        nginx: {
          docroot: {
            owner: "vagrant",
            group: "vagrant",
            path: "/var/www/application/current/app/webroot",
            force_create: true
          },
          default: {
            fastcgi_params: { CAKE_ENV: "deploy" }
          },
          test: {
            available: true,
            fastcgi_params: { CAKE_ENV: "test" }
          }
        }
      }
      chef.run_list = %w[
        recipe[apt]
        recipe[phpenv::default]]
      end
    end  
end