# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opscode_ubuntu-14.04_chef-provisionerless"
  config.vm.define :develop do |develop|
    develop.vm.network :private_network, ip: "192.168.33.10"
	develop.vm.synced_folder "./application", "/var/www/application/current"
	config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end

  config.vm.define :ci do |ci|
    ci.vm.network :private_network, ip: "192.168.33.100"
	config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end

  config.vm.define :deploy do |deploy|
    deploy.vm.network :private_network, ip: "192.168.33.200"
	config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end
end
