VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #define develop machine
  config.vm.define "develop" do |develop|
	
	#Box name
  	develop.vm.box = "ubuntu-14.04"
	
	#Host name
	develop.vm.hostname = "develop"
	
	# Create a private network, which allows host-only access to the machine
	# using a specific IP.
	develop.vm.network "private_network", ip: "192.168.33.10"
	
  end
  
  #define ci machine
  config.vm.define "ci" do |ci|
  
	#Box name
  	ci.vm.box = "ubuntu-14.04"
	
	#Host name
	ci.vm.hostname = "ci"
	
	# Create a private network, which allows host-only access to the machine
	# using a specific IP.
	ci.vm.network "private_network", ip: "192.168.33.100"
  
  end
  
  #define deploy machine
  config.vm.define "deploy" do |deploy|
  
	#Box name
  	deploy.vm.box = "ubuntu-14.04"
	
	#Host name
	deploy.vm.hostname = "deploy"
	
	# Create a private network, which allows host-only access to the machine
	# using a specific IP.
	deploy.vm.network "private_network", ip: "192.168.33.200"
  
  end

end
